### ISSUE TITLE
Make storage configurable via config.yml

### ISSUE THREAD

**Issue by Partyschaum** [Jimdo/reportbook#403]
Currently the different storages are hard coded into `ApplicationService::create()` and depend on the `APPLICATION_ENV`.

I want to be able to configure the storage via the `config.yml`.

For example:
```
dev:
  storage: mysql
test:
  storage: mongo
production:
  storage: mongo
```

To create the different repositories use the a [factory](https://en.wikipedia.org/wiki/Factory_(object-oriented_programming)). I think of a `RepositoryFactory` which creates the different repos like this:

```
$repositoryFactory = new RepositoryFactory(...);
$userRepository = $repositoryFactory->createUserRepository();
$reportRepository = $repositoryFactory->createReportRepository();
```
